answers = {
  "The original Sumerian poems that would become the Epic of Gilgamesh were composed": -2100,
  "The last Woolly Mammoths died out on Wrangel Island": -1700,
  "Homer wrote/recorded the epic poems the Iliad and the Odyssey": -700,
  "The Qin dynasty built Qin Shi Huang's Mausoleum guarded by the life-sized Terracotta Army": -300,
  "The Roman conquest of Britain began": 43,
  "Mt. Vesuvius erupted, destroying Pompeii": 79,  
  "The Prophet Muhammad (PBUH) was born": 570, 
  "The Norse viking Erik the Red colonized Greenland": 985, 
  "The Western (Catholic) and Eastern Orthodox Christian churches separated from each other in the Great Schism": 1054,
  "The Hundred Years’ War began": 1337,
  "The Hundred Years’ War ended": 1453,
  "Michelangelo finished the Statue of David": 1504,
  "Martin Luther wrote the Ninety-five Theses": 1517,
  "西遊記 (Journey to the West) was published": 1592,
  "Don Quixote was published": 1605,
  "The storming of the Bastille": 1789,
  "Beethoven’s 5th Symphony premiered": 1808,
  "The U.S. population surpassed the U.K. population": 1860,
  "First known usage of the word “movie”": 1909,
  "Nabisco trademarked the “Oreo biscuit”": 1912,
  "The Partition of British India into the independent dominions of India and Pakistan": 1947,
  "Alaska and Hawaii became states": 1959,
  "Cien años de soledad (One Hundred Years of Solitude) was published": 1967,
  "The Stonewall Uprising": 1969,
  "Exxon Mobile internally released a memo “The Greenhouse Effect,” acknowledging human-caused climate change": 1977,
  "Halley’s Comet appeared most recently": 1986,
  "Brickley’s Ice Cream opened": 1995,
  "The first video was uploaded to YouTube": 2005,
  "Buddy Cianci last ran for mayor of Providence": 2014,
  "Humans captured a photographic image of a black hole for the first time": 2019,
}

festival_guess = [
  "The original Sumerian poems that would become the Epic of Gilgamesh were composed",
  "The Qin dynasty built Qin Shi Huang's Mausoleum guarded by the life-sized Terracotta Army",
  "Homer wrote/recorded the epic poems the Iliad and the Odyssey",
  "The last Woolly Mammoths died out on Wrangel Island",
  "Mt. Vesuvius erupted, destroying Pompeii",
  "The Roman conquest of Britain began",
  "The Prophet Muhammad (PBUH) was born",
  "The Norse viking Erik the Red colonized Greenland",
  "The Hundred Years’ War began",
  "西遊記 (Journey to the West) was published",
  "The Hundred Years’ War ended",
  "Martin Luther wrote the Ninety-five Theses",
  "The Western (Catholic) and Eastern Orthodox Christian churches separated from each other in the Great Schism",
  "Michelangelo finished the Statue of David",
  "Don Quixote was published",
  "The storming of the Bastille",
  "Beethoven’s 5th Symphony premiered",
  "Cien años de soledad (One Hundred Years of Solitude) was published",
  "Nabisco trademarked the “Oreo biscuit”",
  "First known usage of the word “movie”",
  "The Partition of British India into the independent dominions of India and Pakistan",
  "Alaska and Hawaii became states",
  "Exxon Mobile internally released a memo “The Greenhouse Effect,” acknowledging human-caused climate change",
  "The Stonewall Uprising",
  "The U.S. population surpassed the U.K. population",
  "Halley’s Comet appeared most recently",
  "Brickley’s Ice Cream opened",
  "The first video was uploaded to YouTube",
  "Buddy Cianci last ran for mayor of Providence",
  "Humans captured a photographic image of a black hole for the first time"
]

frijoles_guess = [
  "Mt. Vesuvius erupted, destroying Pompeii",
  "The Prophet Muhammad (PBUH) was born",
  "The original Sumerian poems that would become the Epic of Gilgamesh were composed",
  "Homer wrote/recorded the epic poems the Iliad and the Odyssey",
  "The Norse viking Erik the Red colonized Greenland",
  "The Qin dynasty built Qin Shi Huang's Mausoleum guarded by the life-sized Terracotta Army",
  "西遊記 (Journey to the West) was published",
  "The Roman conquest of Britain began",
  "The Hundred Years’ War began",
  "The Hundred Years’ War ended",
  "Michelangelo finished the Statue of David",
  "Martin Luther wrote the Ninety-five Theses",
  "The Western (Catholic) and Eastern Orthodox Christian churches separated from each other in the Great Schism",
  "The storming of the Bastille",
  "Cien años de soledad (One Hundred Years of Solitude) was published",
  "Don Quixote was published",
  "Beethoven’s 5th Symphony premiered",
  "The U.S. population surpassed the U.K. population",
  "The last Woolly Mammoths died out on Wrangel Island",
  "First known usage of the word “movie”",
  "The Partition of British India into the independent dominions of India and Pakistan",
  "Nabisco trademarked the “Oreo biscuit”",
  "The Stonewall Uprising",
  "Alaska and Hawaii became states",
  "Exxon Mobile internally released a memo “The Greenhouse Effect,” acknowledging human-caused climate change",
  "Halley’s Comet appeared most recently",
  "Buddy Cianci last ran for mayor of Providence",
  "Brickley’s Ice Cream opened",
  "The first video was uploaded to YouTube",
  "Humans captured a photographic image of a black hole for the first time"
]

knowers_guess = [
  "The last Woolly Mammoths died out on Wrangel Island",
  "The original Sumerian poems that would become the Epic of Gilgamesh were composed",
  "Homer wrote/recorded the epic poems the Iliad and the Odyssey",
  "西遊記 (Journey to the West) was published",
  "Mt. Vesuvius erupted, destroying Pompeii",
  "The Roman conquest of Britain began",
  "The Prophet Muhammad (PBUH) was born",
  "The Norse viking Erik the Red colonized Greenland",
  "The Western (Catholic) and Eastern Orthodox Christian churches separated from each other in the Great Schism",
  "The Qin dynasty built Qin Shi Huang's Mausoleum guarded by the life-sized Terracotta Army",
  "The Hundred Years’ War began",
  "The Hundred Years’ War ended",
  "Martin Luther wrote the Ninety-five Theses",
  "Michelangelo finished the Statue of David",
  "Don Quixote was published",
  "The storming of the Bastille",
  "Beethoven’s 5th Symphony premiered",
  "The U.S. population surpassed the U.K. population",
  "Alaska and Hawaii became states",
  "First known usage of the word “movie”",
  "The Partition of British India into the independent dominions of India and Pakistan",
  "Brickley’s Ice Cream opened",
  "Nabisco trademarked the “Oreo biscuit”",
  "Cien años de soledad (One Hundred Years of Solitude) was published",
  "The Stonewall Uprising",
  "Halley’s Comet appeared most recently",
  "Buddy Cianci last ran for mayor of Providence",
  "The first video was uploaded to YouTube",
  "Exxon Mobile internally released a memo “The Greenhouse Effect,” acknowledging human-caused climate change",
  "Humans captured a photographic image of a black hole for the first time"
]

olivia_guess = [
  "The last Woolly Mammoths died out on Wrangel Island",
  "The original Sumerian poems that would become the Epic of Gilgamesh were composed",
  "Homer wrote/recorded the epic poems the Iliad and the Odyssey",
  "The Roman conquest of Britain began",
  "The Qin dynasty built Qin Shi Huang's Mausoleum guarded by the life-sized Terracotta Army",
  "Mt. Vesuvius erupted, destroying Pompeii",
  "The Prophet Muhammad (PBUH) was born",
  "The Western (Catholic) and Eastern Orthodox Christian churches separated from each other in the Great Schism",
  "The Norse viking Erik the Red colonized Greenland",
  "The Hundred Years’ War began",
  "The Hundred Years’ War ended",
  "Michelangelo finished the Statue of David",
  "Martin Luther wrote the Ninety-five Theses",
  "Don Quixote was published",
  "Beethoven’s 5th Symphony premiered",
  "The storming of the Bastille",
  "The U.S. population surpassed the U.K. population",
  "Cien años de soledad (One Hundred Years of Solitude) was published",
  "西遊記 (Journey to the West) was published",
  "First known usage of the word “movie”",
  "Nabisco trademarked the “Oreo biscuit”",
  "The Partition of British India into the independent dominions of India and Pakistan",
  "Alaska and Hawaii became states",
  "The Stonewall Uprising",
  "Exxon Mobile internally released a memo “The Greenhouse Effect,” acknowledging human-caused climate change",
  "Brickley’s Ice Cream opened",
  "Halley’s Comet appeared most recently",
  "The first video was uploaded to YouTube",
  "Buddy Cianci last ran for mayor of Providence",
  "Humans captured a photographic image of a black hole for the first time",
]